

name: davgarram

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [opened, transferred]
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  log:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Log
      if: (github.event_name =="workflow_dispatch") 
      run: echo "${{ github.actor.login }} activated this manually"
      else:
      run: echo "${{ github.actor.login }} created or moved an issue"
