

name: davgarram

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [opened]
  project_card:
    types: [moved]
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  manual:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Log manual
      if: (github.event_name =='workflow_dispatch') 
      run: echo "${{ github.actor}} activated this manually"
  issue:
      
      runs-on: ubuntu-latest
      steps:
        - name: Log automatico (issue)
          if: (github.event_name =='issues'||github.event_name =='project_card') 
          run: echo "${{ github.actor}} created or moved an issue"
