

name: davgarram

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [opened, transferred]
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  manual:
    if: (github.event_name =="workflow_dispatch") 
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Log manual
      run: echo "${{ github.actor.login }} activated this manually"
  issue:
      if: (github.event_name =="issues") 
      runs-on: ubuntu-latest
      steps:
        - name: Log automatico (issue)
          run: echo "${{ github.actor.login }} created or moved an issue"
